/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/wallet/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateWallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/paymentMethods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPaymentMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoice/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetInvoice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["PatchInvoice"];
        trace?: never;
    };
    "/v1/invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoice/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CancelInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoice/{id}/prolong": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProlongInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invoice/{id}/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SubscribeInvoice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetInvoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ErrorStatusCode: "INVALID_ARGUMENT" | "NOT_FOUND" | "ALREADY_EXISTS" | "INTERNAL" | "UNAUTHENTICATED" | "PERMISSION_DENIED";
        ErrorResponse: {
            code: components["schemas"]["ErrorStatusCode"];
            errors: string[];
        };
        ChainTokenStatic: {
            /** @description Chain name */
            chain: string;
            /** @description Token name */
            token: string;
            /** @description Payment method name (token + chain) */
            methodName: string;
            /** @description Payment address */
            address: string;
        };
        StaticWallet: {
            /**
             * Format: uuid
             * @description Wallet id
             */
            id: string;
            /** @description ID in the client's system (specified when creating a wallet) */
            orderId: string;
            /** @description Wallet addresses for payment */
            addresses: components["schemas"]["ChainTokenStatic"][];
        };
        /** Format: uuid */
        UUID: string;
        CreateStaticWalletRequest: {
            /** @description ID in the client's system */
            orderId: string;
        };
        Rate: {
            name: string;
            rate: string;
        };
        PaymentMethod: {
            /** @description Chain name */
            chain: string;
            /** @description Token name */
            token: string;
            /** @description Payment method name (token + chain) */
            methodName: string;
            /** @description Payment method icon */
            icon: string;
            /** @description Chain icon */
            chainIcon: string;
            /** @description Token icon */
            tokenIcon: string;
        };
        PaymentMethods: {
            paymentMethods: components["schemas"]["PaymentMethod"][];
        };
        /** @enum {string} */
        InvoiceStatus: "WAITING_SELECTION" | "WAITING_PAYMENT" | "COMPLETE" | "EXPIRED" | "OVER_PAID" | "UNDER_PAID";
        LastTransaction: {
            /** @description Chain name */
            chain: string;
            /** @description Transaction Hash */
            txid: string;
        };
        PaymentDetails: {
            /** @description Chain name */
            chain: string;
            /** @description Token name */
            token: string;
            /** @description Payment address */
            address?: string;
            /**
             * Format: decimal
             * @description Expected payment amount in tokens
             */
            amount?: string;
        };
        Invoice: {
            /**
             * Format: uuid
             * @description Invoice id
             */
            id: string;
            /** @description ID in the client's system (specified when creating an invoice) */
            orderId: string;
            /** @description Merchant's name */
            merchantName: string;
            /**
             * Format: decimal
             * @description Original order amount in USD (excluding service fee)
             */
            amount?: string;
            /**
             * Format: decimal
             * @description Amount to pay in USD (excluding service fee if feeIncluded)
             */
            paymentAmount?: string;
            /**
             * Format: decimal
             * @description Total amount actually paid by the customer in USD
             */
            paidAmount: string;
            /** @description If true, the service fee is added to paymentDetails.amount (paid by customer) */
            feeIncluded: boolean;
            /**
             * Format: decimal
             * @description Allowed payment deviation (0 to 0.05). If within range, status is COMPLETE
             */
            accuracy: string;
            /**
             * Format: decimal
             * @description Service fee fraction (e.g., 0.02 for 2%)
             */
            feeRate: string;
            /**
             * Format: decimal
             * @description Expected credit to merchant balance if paid 100%
             */
            expectedMerchantAmount: string;
            /**
             * Format: decimal
             * @description Actual amount already credited to merchant balance (paidAmount minus fee)
             */
            merchantPaidAmount: string;
            /**
             * Format: date-time
             * @description ISO 8601 creation date
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description ISO 8601 expiration date
             */
            expiredAt: string;
            /**
             * Format: date-time
             * @description Recorded original expiration date if prolonged
             */
            originalExpiredAt?: string;
            /**
             * Format: date-time
             * @description ISO 8601 cancellation date
             */
            canceledAt?: string;
            /** @description Current invoice status */
            status: components["schemas"]["InvoiceStatus"];
            /**
             * Format: uri
             * @description Public payment page link
             */
            url: string;
            /**
             * Format: uri
             * @description Redirect URL after successful payment
             */
            urlSuccess?: string;
            /**
             * Format: uri
             * @description Redirect URL after failure (canceled or expired)
             */
            urlReturn?: string;
            /**
             * Format: uri
             * @description Merchant's support contact link
             */
            supportLink?: string;
            /** @description Info about the most recent incoming transaction */
            lastTransaction?: components["schemas"]["LastTransaction"];
            /** @description Information about the selected payment method and the amount to be paid. */
            paymentDetails?: components["schemas"]["PaymentDetails"];
        };
        ChainToken: {
            /** @description Chain name */
            chain: string;
            /** @description Token name */
            token: string;
        };
        CreateInvoiceRequest: {
            /** @description ID in the client's system */
            orderId: string;
            /**
             * Format: decimal
             * @description Invoice amount in USD. If omitted, any payment amount will result in COMPLETE status
             */
            amount?: string;
            /**
             * @description If the option is enabled, the service fee will be added to the amount.
             * @default false
             */
            feeIncluded?: boolean;
            /**
             * Format: decimal
             * @description What deviation from amount should still be marked COMPLETE. From 0 to 0.05 where 0.05 is 5%
             * @default 0
             */
            accuracy?: string;
            /**
             * Format: uri
             * @description Redirect after successful payment
             */
            urlSuccess?: string;
            /**
             * Format: uri
             * @description Redirect after failure (canceled or expired)
             */
            urlReturn?: string;
            /** @description Selected chain and token */
            chainToken?: components["schemas"]["ChainToken"];
        };
        PatchInvoiceRequest: {
            /**
             * Format: decimal
             * @description Invoice amount, can only be set if not specified during creation
             */
            amount?: string;
            /** @description Chain and token, can only be set if not specified during creation */
            chainToken?: components["schemas"]["ChainToken"];
        };
        Invoices: {
            /** @description Requested invoices */
            invoices: components["schemas"]["Invoice"][];
            /**
             * Format: int32
             * @description How many invoices in total (for pagination)
             */
            totalCount: number;
        };
        GetHistoryRequest: {
            /**
             * Format: date-time
             * @description Start date for filtering in ISO 8601 format
             */
            fromDate: string;
            /**
             * Format: date-time
             * @description End date for filtering in ISO 8601 format
             */
            toDate?: string;
            /**
             * Format: int32
             * @description Maximum number of items to output. No more than 1000.
             * @default 1000
             */
            limit?: number;
            /**
             * @description If specified, will return notifications that have not yet been acknowledged.
             * @default false
             */
            notNotified?: boolean;
        };
        StaticWalletNotification: {
            /**
             * Format: uuid
             * @description Wallet id
             */
            id: string;
            /** @description ID in the client's system (specified when creating a wallet) */
            orderId: string;
        };
        Transaction: {
            /** @description Transaction hash */
            txid: string;
            /** @description Chain name */
            chain: string;
            /** @description Token name */
            token: string;
            /**
             * Format: decimal
             * @description Amount in tokens
             */
            value: string;
            /**
             * Format: decimal
             * @description Amount in USD, before deducting the commission
             */
            usd: string;
            /**
             * Format: decimal
             * @description Service fee in USD
             */
            fee: string;
            /** @description Wallet info */
            wallet?: components["schemas"]["StaticWalletNotification"];
            /**
             * Format: date-time
             * @description Payment processing date in ISO 8601 format
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Date of funds sent in ISO 8601 format
             */
            blockCreatedAt: string;
            /**
             * Format: decimal
             * @description Amount to be credited to the merchant, after deducting the commission
             */
            merchantAmount: string;
            /**
             * Format: uuid
             * @description Transaction id
             */
            id: string;
        };
        Transactions: {
            /** @description Requested transactions */
            transactions: components["schemas"]["Transaction"][];
            /**
             * Format: int32
             * @description How many transactions in total (for pagination)
             */
            totalCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["UUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaticWallet"];
                };
            };
            /** @description INVALID_ARGUMENT */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CreateWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStaticWalletRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaticWallet"];
                };
            };
            /** @description INVALID_ARGUMENT */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHENTICATED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rate"][];
                };
            };
        };
    };
    GetPaymentMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentMethods"];
                };
            };
        };
    };
    GetInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["UUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            /** @description INVALID_ARGUMENT */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHENTICATED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    PatchInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["UUID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchInvoiceRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            /** @description INVALID_ARGUMENT */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHENTICATED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CreateInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvoiceRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            /** @description INVALID_ARGUMENT */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHENTICATED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CancelInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["UUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            /** @description INVALID_ARGUMENT */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHENTICATED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ProlongInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["UUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            /** @description INVALID_ARGUMENT */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHENTICATED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    SubscribeInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["UUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            /** @description INVALID_ARGUMENT */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHENTICATED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetInvoices: {
        parameters: {
            query: {
                /** @description Start date for filtering in ISO 8601 format */
                fromDate: string;
                /** @description End date for filtering in ISO 8601 format */
                toDate?: string;
                /** @description Maximum number of items to output. No more than 1000. */
                limit?: number;
                /** @description If specified, will return notifications that have not yet been acknowledged. */
                notNotified?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoices"];
                };
            };
            /** @description INVALID_ARGUMENT */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHENTICATED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetTransactions: {
        parameters: {
            query: {
                /** @description Start date for filtering in ISO 8601 format */
                fromDate: string;
                /** @description End date for filtering in ISO 8601 format */
                toDate?: string;
                /** @description Maximum number of items to output. No more than 1000. */
                limit?: number;
                /** @description If specified, will return notifications that have not yet been acknowledged. */
                notNotified?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transactions"];
                };
            };
            /** @description INVALID_ARGUMENT */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHENTICATED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
